framework:
    router:
        utf8: true
<<<<<<< HEAD
=======

        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
>>>>>>> eead9363a128f29c44d68a20104a55e4cf0ea815
